import { RunMaterialReviewQueue } from '@/components/academy/RunMaterialReviewQueue'
import Link from 'next/link'
import { BookOpen, Plus } from 'lucide-react'
import { AcademyShell } from '@/components/academy/AcademyShell'
import { AcademyAdminNav } from '@/components/academy/AcademyAdminNav'
import { AcademyEmptyState } from '@/components/academy/AcademyEmptyState'
import { COURSE_FORMAT_LABELS, COURSE_LEVEL_LABELS } from '@/components/academy/catalog/catalog-filters'
import { Button } from '@/components/ui/button'
import { getReviewQueue, getLegacyReviewQueue } from '@/lib/actions/courses-admin'

export const dynamic = 'force-dynamic'

export default async function AdminAkademiaPage({ searchParams }: { searchParams: { page?: string } }) {
    const requestedPage = Number(searchParams.page ?? '1')
    const page = Number.isSafeInteger(requestedPage) && requestedPage > 0 ? requestedPage : 1
    const [result, legacy] = await Promise.all([getReviewQueue(page), getLegacyReviewQueue()])
    return <AcademyShell activeTab="admin" access={{ isAdmin: true, canTeach: true }} title="Akceptacja szkoleń" description="Sprawdź program, materiały i zasady ukończenia przed opublikowaniem konkretnej wersji." action={<Button asChild><Link href="/learning/tworze/nowy?type=company"><Plus aria-hidden="true" />Nowe szkolenie firmowe</Link></Button>}>
        <AcademyAdminNav active="review" />
        {!result.success ? <AcademyEmptyState variant="error" title="Nie udało się wczytać kolejki" description="Odśwież stronę i spróbuj ponownie. Decyzje dotyczące szkoleń pozostają bez zmian." /> : result.data.total === 0 ? <AcademyEmptyState title="Wszystkie zgłoszenia rozpatrzone" description="Nowe wersje przesłane przez trenerów pojawią się tutaj. Terminy spotkań zatwierdzisz w szczegółach edycji." /> : <section className="space-y-4"><p className="text-sm text-muted-foreground">Wersje oczekujące na decyzję: <strong className="text-foreground">{result.data.total}</strong></p>{result.data.items.length === 0 ? <AcademyEmptyState title="Brak zgłoszeń na tej stronie" description="Wróć do wcześniejszej strony kolejki, aby sprawdzić oczekujące wersje." /> : result.data.items.map((course) => <article key={course.version_id ?? course.id} className="flex flex-col justify-between gap-4 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-start"><div className="min-w-0 space-y-3"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-warning/10 px-2.5 py-1 text-warning">Oczekuje na akceptację</span><span className="text-muted-foreground">{course.version_number ? `Wersja ${course.version_number}` : 'Zgłoszona wersja'} · {COURSE_FORMAT_LABELS[course.delivery_mode ?? 'self_paced']}</span></div><h2 className="text-lg font-semibold">{course.title}</h2>{course.description && <p className="line-clamp-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">{course.description}</p>}<p className="text-xs text-muted-foreground">{course.author_name || 'Autor szkolenia'} · {course.category} · {COURSE_LEVEL_LABELS[course.level]}</p></div><Button asChild variant="outline" className="shrink-0"><Link href={`/admin/learning/${course.id}`}><BookOpen aria-hidden="true" />Sprawdź wersję</Link></Button></article>)}<nav aria-label="Strony kolejki akceptacji" className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>{page > 1 ? <Link className="text-primary hover:underline" href={`/admin/learning?page=${page - 1}`}>← Poprzednia strona</Link> : null}</span><span className="text-muted-foreground">Strona {page} z {Math.max(1, Math.ceil(result.data.total / result.data.pageSize))}</span><span>{page * result.data.pageSize < result.data.total ? <Link className="text-primary hover:underline" href={`/admin/learning?page=${page + 1}`}>Następna strona →</Link> : null}</span></nav></section>}
        {!legacy.success ? <p role="alert" className="text-destructive">Nie udało się wczytać historycznych publikacji.</p> : legacy.data.length > 0 && <section className="space-y-4"><h2 className="text-lg font-semibold">Historyczne publikacje do sprawdzenia</h2><p className="text-sm text-muted-foreground">Nowe zapisy są wstrzymane do niezależnej akceptacji. Dotychczasowe postępy i certyfikaty pozostają dostępne.</p>{legacy.data.map(course => <article key={course.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border bg-card p-5"><h3 className="font-medium">{course.title}</h3><Button asChild variant="outline"><Link href={`/admin/learning/${course.id}?legacy=1`}>Sprawdź opublikowaną wersję</Link></Button></article>)}</section>}
        <RunMaterialReviewQueue />
    </AcademyShell>
}
