DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
Checks 12
MaxAttempts 3
ConnectTimeout 20
ReceiveTimeout 120
TestDatabases yes
ScriptedUpdates yes
NotifyClamd /etc/clamav/clamd.conf
LogTime yes
LogVerbose no
