// Auto-generated by Supabase CLI.
// Run `npm run db:types` to regenerate.
// Last generated: 2026-05-12 (Phase 18.5)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_access_list: {
        Row: {
          added_by: string | null
          created_at: string | null
          email: string
          id: string
        }
        Insert: {
          added_by?: string | null
          created_at?: string | null
          email: string
          id?: string
        }
        Update: {
          added_by?: string | null
          created_at?: string | null
          email?: string
          id?: string
        }
        Relationships: []
      }
      app_documents: {
        Row: {
          ai_indexed: boolean | null
          ai_indexed_at: string | null
          category: string
          created_at: string
          current_status: string
          description: string | null
          id: string
          is_archived: boolean | null
          is_public: boolean | null
          owner_id: string
          text_content: string | null
          title: string
          updated_at: string
        }
        Insert: {
          ai_indexed?: boolean | null
          ai_indexed_at?: string | null
          category: string
          created_at?: string
          current_status?: string
          description?: string | null
          id?: string
          is_archived?: boolean | null
          is_public?: boolean | null
          owner_id: string
          text_content?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          ai_indexed?: boolean | null
          ai_indexed_at?: string | null
          category?: string
          created_at?: string
          current_status?: string
          description?: string | null
          id?: string
          is_archived?: boolean | null
          is_public?: boolean | null
          owner_id?: string
          text_content?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_documents_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attendance_records: {
        Row: {
          created_at: string
          created_by: string | null
          date: string
          id: string
          location: string | null
          note: string | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          date: string
          id?: string
          location?: string | null
          note?: string | null
          status: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          date?: string
          id?: string
          location?: string | null
          note?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          created_at: string | null
          details: Json | null
          id: string
          ip_address: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string | null
          details?: Json | null
          id?: string
          ip_address?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string | null
          details?: Json | null
          id?: string
          ip_address?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      compass_assist_knowledge: {
        Row: {
          category: string | null
          content: string
          created_at: string | null
          embedding: string | null
          id: string
          is_active: boolean | null
          source_id: string | null
          source_type: string | null
          tags: string[] | null
          title: string
          updated_at: string | null
        }
        Insert: {
          category?: string | null
          content: string
          created_at?: string | null
          embedding?: string | null
          id?: string
          is_active?: boolean | null
          source_id?: string | null
          source_type?: string | null
          tags?: string[] | null
          title: string
          updated_at?: string | null
        }
        Update: {
          category?: string | null
          content?: string
          created_at?: string | null
          embedding?: string | null
          id?: string
          is_active?: boolean | null
          source_id?: string | null
          source_type?: string | null
          tags?: string[] | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      compass_assist_tickets: {
        Row: {
          created_at: string | null
          id: string
          message: string
          priority: string | null
          status: string | null
          subject: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          message: string
          priority?: string | null
          status?: string | null
          subject: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          message?: string
          priority?: string | null
          status?: string | null
          subject?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      contracts: {
        Row: {
          client_name: string
          consultant_id: string
          contract_number: string | null
          created_at: string | null
          created_by: string | null
          currency: string | null
          deleted_at: string | null
          end_date: string
          extension_count: number | null
          health_score: number | null
          hourly_rate: number | null
          hours_per_week: number | null
          id: string
          last_health_check: string | null
          monthly_rate: number | null
          notes: string | null
          original_end_date: string | null
          position: string
          project_name: string
          start_date: string
          status: string
          updated_at: string | null
          work_location: string | null
          work_mode: string | null
        }
        Insert: {
          client_name: string
          consultant_id: string
          contract_number?: string | null
          created_at?: string | null
          created_by?: string | null
          currency?: string | null
          deleted_at?: string | null
          end_date: string
          extension_count?: number | null
          health_score?: number | null
          hourly_rate?: number | null
          hours_per_week?: number | null
          id?: string
          last_health_check?: string | null
          monthly_rate?: number | null
          notes?: string | null
          original_end_date?: string | null
          position: string
          project_name: string
          start_date: string
          status?: string
          updated_at?: string | null
          work_location?: string | null
          work_mode?: string | null
        }
        Update: {
          client_name?: string
          consultant_id?: string
          contract_number?: string | null
          created_at?: string | null
          created_by?: string | null
          currency?: string | null
          deleted_at?: string | null
          end_date?: string
          extension_count?: number | null
          health_score?: number | null
          hourly_rate?: number | null
          hours_per_week?: number | null
          id?: string
          last_health_check?: string | null
          monthly_rate?: number | null
          notes?: string | null
          original_end_date?: string | null
          position?: string
          project_name?: string
          start_date?: string
          status?: string
          updated_at?: string | null
          work_location?: string | null
          work_mode?: string | null
        }
        Relationships: []
      }
      conversation_participants: {
        Row: {
          conversation_id: string
          joined_at: string | null
          last_read_at: string | null
          role: string
          user_id: string
        }
        Insert: {
          conversation_id: string
          joined_at?: string | null
          last_read_at?: string | null
          role?: string
          user_id: string
        }
        Update: {
          conversation_id?: string
          joined_at?: string | null
          last_read_at?: string | null
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_participants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          created_at: string | null
          id: string
          last_message_at: string | null
          name: string | null
          owner_id: string | null
          type: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          last_message_at?: string | null
          name?: string | null
          owner_id?: string | null
          type: string
        }
        Update: {
          created_at?: string | null
          id?: string
          last_message_at?: string | null
          name?: string | null
          owner_id?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_answers: {
        Row: {
          answer_text: string
          created_at: string
          id: string
          is_author_answer: boolean
          question_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          answer_text: string
          created_at?: string
          id?: string
          is_author_answer?: boolean
          question_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          answer_text?: string
          created_at?: string
          id?: string
          is_author_answer?: boolean
          question_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "course_questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_answers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_enrollments: {
        Row: {
          certificate_hash: string | null
          certificate_issued_at: string | null
          completed_at: string | null
          completed_lessons: string[]
          course_id: string
          enrolled_at: string
          id: string
          last_accessed_at: string | null
          last_accessed_lesson_id: string | null
          last_inactivity_email_at: string | null
          lesson_completion_dates: Json
          points_awarded: boolean
          user_id: string
        }
        Insert: {
          certificate_hash?: string | null
          certificate_issued_at?: string | null
          completed_at?: string | null
          completed_lessons?: string[]
          course_id: string
          enrolled_at?: string
          id?: string
          last_accessed_at?: string | null
          last_accessed_lesson_id?: string | null
          last_inactivity_email_at?: string | null
          lesson_completion_dates?: Json
          points_awarded?: boolean
          user_id: string
        }
        Update: {
          certificate_hash?: string | null
          certificate_issued_at?: string | null
          completed_at?: string | null
          completed_lessons?: string[]
          course_id?: string
          enrolled_at?: string
          id?: string
          last_accessed_at?: string | null
          last_accessed_lesson_id?: string | null
          last_inactivity_email_at?: string | null
          lesson_completion_dates?: Json
          points_awarded?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_enrollments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_enrollments_last_accessed_lesson_id_fkey"
            columns: ["last_accessed_lesson_id"]
            isOneToOne: false
            referencedRelation: "course_lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_enrollments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_lessons: {
        Row: {
          ai_summary: string | null
          ai_summary_generated_at: string | null
          attachments: Json
          content_md: string | null
          course_id: string
          created_at: string
          estimated_minutes: number | null
          id: string
          order_index: number
          title: string
          unlock_after_days: number
          updated_at: string
          video_url: string | null
        }
        Insert: {
          ai_summary?: string | null
          ai_summary_generated_at?: string | null
          attachments?: Json
          content_md?: string | null
          course_id: string
          created_at?: string
          estimated_minutes?: number | null
          id?: string
          order_index: number
          title: string
          unlock_after_days?: number
          updated_at?: string
          video_url?: string | null
        }
        Update: {
          ai_summary?: string | null
          ai_summary_generated_at?: string | null
          attachments?: Json
          content_md?: string | null
          course_id?: string
          created_at?: string
          estimated_minutes?: number | null
          id?: string
          order_index?: number
          title?: string
          unlock_after_days?: number
          updated_at?: string
          video_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "course_lessons_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      course_questions: {
        Row: {
          answers_count: number
          course_id: string
          created_at: string
          id: string
          is_resolved: boolean
          lesson_id: string | null
          question_text: string
          updated_at: string
          user_id: string
        }
        Insert: {
          answers_count?: number
          course_id: string
          created_at?: string
          id?: string
          is_resolved?: boolean
          lesson_id?: string | null
          question_text: string
          updated_at?: string
          user_id: string
        }
        Update: {
          answers_count?: number
          course_id?: string
          created_at?: string
          id?: string
          is_resolved?: boolean
          lesson_id?: string | null
          question_text?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_questions_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_questions_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "course_lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_questions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_quiz_attempts: {
        Row: {
          answers: Json
          attempted_at: string
          course_id: string
          enrollment_id: string
          id: string
          passed: boolean
          score_percent: number
          user_id: string
        }
        Insert: {
          answers: Json
          attempted_at?: string
          course_id: string
          enrollment_id: string
          id?: string
          passed: boolean
          score_percent: number
          user_id: string
        }
        Update: {
          answers?: Json
          attempted_at?: string
          course_id?: string
          enrollment_id?: string
          id?: string
          passed?: boolean
          score_percent?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_quiz_attempts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_quiz_attempts_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "course_enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_quiz_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_quiz_options: {
        Row: {
          created_at: string
          id: string
          is_correct: boolean
          option_text: string
          order_index: number
          question_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_correct?: boolean
          option_text: string
          order_index: number
          question_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_correct?: boolean
          option_text?: string
          order_index?: number
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_quiz_options_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "course_quiz_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      course_quiz_questions: {
        Row: {
          course_id: string
          created_at: string
          id: string
          order_index: number
          question_text: string
        }
        Insert: {
          course_id: string
          created_at?: string
          id?: string
          order_index: number
          question_text: string
        }
        Update: {
          course_id?: string
          created_at?: string
          id?: string
          order_index?: number
          question_text?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_quiz_questions_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      course_ratings: {
        Row: {
          comment: string | null
          course_id: string
          created_at: string
          id: string
          rating: number
          user_id: string
        }
        Insert: {
          comment?: string | null
          course_id: string
          created_at?: string
          id?: string
          rating: number
          user_id: string
        }
        Update: {
          comment?: string | null
          course_id?: string
          created_at?: string
          id?: string
          rating?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_ratings_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_ratings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_survey_responses: {
        Row: {
          best_part: string | null
          course_id: string
          enrollment_id: string
          id: string
          improvement_suggestion: string | null
          nps_score: number | null
          submitted_at: string
          user_id: string
        }
        Insert: {
          best_part?: string | null
          course_id: string
          enrollment_id: string
          id?: string
          improvement_suggestion?: string | null
          nps_score?: number | null
          submitted_at?: string
          user_id: string
        }
        Update: {
          best_part?: string | null
          course_id?: string
          enrollment_id?: string
          id?: string
          improvement_suggestion?: string | null
          nps_score?: number | null
          submitted_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_survey_responses_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_survey_responses_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "course_enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_survey_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          author_id: string
          avg_rating: number
          category: string
          completions_count: number
          course_type: Database["public"]["Enums"]["course_type_t"]
          cover_image_url: string | null
          created_at: string
          description: string | null
          duration_minutes: number | null
          embedding: string | null
          embedding_generated_at: string | null
          enrollments_count: number
          id: string
          is_official: boolean
          level: string
          prerequisite_course_ids: string[]
          published_at: string | null
          ratings_count: number
          rejection_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          slug: string
          status: string
          tags: string[]
          title: string
          updated_at: string
        }
        Insert: {
          author_id: string
          avg_rating?: number
          category: string
          completions_count?: number
          course_type?: Database["public"]["Enums"]["course_type_t"]
          cover_image_url?: string | null
          created_at?: string
          description?: string | null
          duration_minutes?: number | null
          embedding?: string | null
          embedding_generated_at?: string | null
          enrollments_count?: number
          id?: string
          is_official?: boolean
          level?: string
          prerequisite_course_ids?: string[]
          published_at?: string | null
          ratings_count?: number
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          slug: string
          status?: string
          tags?: string[]
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          avg_rating?: number
          category?: string
          completions_count?: number
          course_type?: Database["public"]["Enums"]["course_type_t"]
          cover_image_url?: string | null
          created_at?: string
          description?: string | null
          duration_minutes?: number | null
          embedding?: string | null
          embedding_generated_at?: string | null
          enrollments_count?: number
          id?: string
          is_official?: boolean
          level?: string
          prerequisite_course_ids?: string[]
          published_at?: string | null
          ratings_count?: number
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          slug?: string
          status?: string
          tags?: string[]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "courses_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "courses_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      document_versions: {
        Row: {
          change_summary: string | null
          created_at: string
          document_id: string
          file_name: string
          file_size: number | null
          file_url: string
          id: string
          uploaded_by: string
          version_number: number
        }
        Insert: {
          change_summary?: string | null
          created_at?: string
          document_id: string
          file_name: string
          file_size?: number | null
          file_url: string
          id?: string
          uploaded_by: string
          version_number: number
        }
        Update: {
          change_summary?: string | null
          created_at?: string
          document_id?: string
          file_name?: string
          file_size?: number | null
          file_url?: string
          id?: string
          uploaded_by?: string
          version_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "document_versions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "app_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_versions_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      favorite_projects: {
        Row: {
          created_at: string
          id: string
          note: string | null
          project_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          note?: string | null
          project_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          note?: string | null
          project_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorite_projects_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      incubator_applications: {
        Row: {
          applicant_id: string
          created_at: string
          id: string
          motivation_md: string
          project_id: string
          status: string
          updated_at: string
        }
        Insert: {
          applicant_id: string
          created_at?: string
          id?: string
          motivation_md: string
          project_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          applicant_id?: string
          created_at?: string
          id?: string
          motivation_md?: string
          project_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "incubator_applications_applicant_id_fkey"
            columns: ["applicant_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incubator_applications_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "incubator_projects"
            referencedColumns: ["id"]
          },
        ]
      }
      incubator_pitches: {
        Row: {
          attachment_urls: string[] | null
          created_at: string
          description_md: string
          equity_ask: string | null
          id: string
          investment_ask_pln: number | null
          nda_accepted_at: string
          review_notes_md: string | null
          reviewer_id: string | null
          status: string
          submitter_id: string
          title: string
          updated_at: string
        }
        Insert: {
          attachment_urls?: string[] | null
          created_at?: string
          description_md: string
          equity_ask?: string | null
          id?: string
          investment_ask_pln?: number | null
          nda_accepted_at: string
          review_notes_md?: string | null
          reviewer_id?: string | null
          status?: string
          submitter_id: string
          title: string
          updated_at?: string
        }
        Update: {
          attachment_urls?: string[] | null
          created_at?: string
          description_md?: string
          equity_ask?: string | null
          id?: string
          investment_ask_pln?: number | null
          nda_accepted_at?: string
          review_notes_md?: string | null
          reviewer_id?: string | null
          status?: string
          submitter_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "incubator_pitches_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incubator_pitches_submitter_id_fkey"
            columns: ["submitter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      incubator_projects: {
        Row: {
          closes_at: string | null
          compensation_model: string | null
          created_at: string
          description_md: string
          id: string
          opens_at: string | null
          owner_id: string
          slug: string
          status: string
          tech_stack: string[] | null
          title: string
          updated_at: string
        }
        Insert: {
          closes_at?: string | null
          compensation_model?: string | null
          created_at?: string
          description_md: string
          id?: string
          opens_at?: string | null
          owner_id: string
          slug: string
          status?: string
          tech_stack?: string[] | null
          title: string
          updated_at?: string
        }
        Update: {
          closes_at?: string | null
          compensation_model?: string | null
          created_at?: string
          description_md?: string
          id?: string
          opens_at?: string | null
          owner_id?: string
          slug?: string
          status?: string
          tech_stack?: string[] | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "incubator_projects_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_path_courses: {
        Row: {
          course_id: string
          created_at: string
          id: string
          is_required: boolean
          order_index: number
          path_id: string
        }
        Insert: {
          course_id: string
          created_at?: string
          id?: string
          is_required?: boolean
          order_index: number
          path_id: string
        }
        Update: {
          course_id?: string
          created_at?: string
          id?: string
          is_required?: boolean
          order_index?: number
          path_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_path_courses_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_path_courses_path_id_fkey"
            columns: ["path_id"]
            isOneToOne: false
            referencedRelation: "learning_paths"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_path_enrollments: {
        Row: {
          completed_at: string | null
          enrolled_at: string
          id: string
          path_id: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          enrolled_at?: string
          id?: string
          path_id: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          enrolled_at?: string
          id?: string
          path_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_path_enrollments_path_id_fkey"
            columns: ["path_id"]
            isOneToOne: false
            referencedRelation: "learning_paths"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_path_enrollments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_paths: {
        Row: {
          author_id: string
          completions_count: number
          cover_image_url: string | null
          created_at: string
          description: string | null
          enrollments_count: number
          estimated_hours: number | null
          id: string
          level: string
          slug: string
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          author_id: string
          completions_count?: number
          cover_image_url?: string | null
          created_at?: string
          description?: string | null
          enrollments_count?: number
          estimated_hours?: number | null
          id?: string
          level?: string
          slug: string
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          completions_count?: number
          cover_image_url?: string | null
          created_at?: string
          description?: string | null
          enrollments_count?: number
          estimated_hours?: number | null
          id?: string
          level?: string
          slug?: string
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_paths_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_requests: {
        Row: {
          created_at: string
          decided_at: string | null
          decided_by: string | null
          decision_note: string | null
          documentation_url: string | null
          end_date: string
          half_day: string | null
          id: string
          leave_type: string
          note: string | null
          outlook_event_id: string | null
          start_date: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          decided_at?: string | null
          decided_by?: string | null
          decision_note?: string | null
          documentation_url?: string | null
          end_date: string
          half_day?: string | null
          id?: string
          leave_type: string
          note?: string | null
          outlook_event_id?: string | null
          start_date: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          decided_at?: string | null
          decided_by?: string | null
          decision_note?: string | null
          documentation_url?: string | null
          end_date?: string
          half_day?: string | null
          id?: string
          leave_type?: string
          note?: string | null
          outlook_event_id?: string | null
          start_date?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leave_requests_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      login_attempts: {
        Row: {
          attempt_time: string | null
          email: string
          id: string
          ip_address: string
          success: boolean | null
        }
        Insert: {
          attempt_time?: string | null
          email: string
          id?: string
          ip_address: string
          success?: boolean | null
        }
        Update: {
          attempt_time?: string | null
          email?: string
          id?: string
          ip_address?: string
          success?: boolean | null
        }
        Relationships: []
      }
      loyalty_rules: {
        Row: {
          category: string
          code: string
          created_at: string
          description: string | null
          id: string
          is_active: boolean | null
          name: string
          points: number
          updated_at: string
        }
        Insert: {
          category: string
          code: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          points: number
          updated_at?: string
        }
        Update: {
          category?: string
          code?: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          points?: number
          updated_at?: string
        }
        Relationships: []
      }
      loyalty_transactions: {
        Row: {
          confirmed_at: string | null
          created_at: string | null
          description: string
          id: string
          points: number
          reverses_id: string | null
          source_id: string | null
          source_type: string
          status: string
          user_id: string
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string | null
          description: string
          id?: string
          points: number
          reverses_id?: string | null
          source_id?: string | null
          source_type: string
          status?: string
          user_id: string
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string | null
          description?: string
          id?: string
          points?: number
          reverses_id?: string | null
          source_id?: string | null
          source_type?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "loyalty_transactions_reverses_id_fkey"
            columns: ["reverses_id"]
            isOneToOne: false
            referencedRelation: "loyalty_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "loyalty_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          attachment_url: string | null
          content: string | null
          conversation_id: string
          created_at: string | null
          id: string
          sender_id: string
          type: string | null
        }
        Insert: {
          attachment_url?: string | null
          content?: string | null
          conversation_id: string
          created_at?: string | null
          id?: string
          sender_id: string
          type?: string | null
        }
        Update: {
          attachment_url?: string | null
          content?: string | null
          conversation_id?: string
          created_at?: string | null
          id?: string
          sender_id?: string
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      news_post_reads: {
        Row: {
          post_id: string
          read_at: string
          user_id: string
        }
        Insert: {
          post_id: string
          read_at?: string
          user_id: string
        }
        Update: {
          post_id?: string
          read_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_post_reads_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "news_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "news_post_reads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      news_posts: {
        Row: {
          audience_role: string[] | null
          author_id: string
          body_md: string
          cover_url: string | null
          created_at: string
          excerpt: string | null
          id: string
          pinned: boolean
          published_at: string | null
          slug: string
          title: string
          updated_at: string
        }
        Insert: {
          audience_role?: string[] | null
          author_id: string
          body_md: string
          cover_url?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          pinned?: boolean
          published_at?: string | null
          slug: string
          title: string
          updated_at?: string
        }
        Update: {
          audience_role?: string[] | null
          author_id?: string
          body_md?: string
          cover_url?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          pinned?: boolean
          published_at?: string | null
          slug?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_posts_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      news_reactions: {
        Row: {
          created_at: string
          id: string
          kind: string
          post_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          post_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          post_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "news_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "news_reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          action_url: string | null
          body_en: string | null
          body_pl: string | null
          created_at: string | null
          expires_at: string | null
          id: string
          is_read: boolean | null
          priority: string | null
          read_at: string | null
          title_en: string
          title_pl: string
          type: string
          user_id: string
        }
        Insert: {
          action_url?: string | null
          body_en?: string | null
          body_pl?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_read?: boolean | null
          priority?: string | null
          read_at?: string | null
          title_en: string
          title_pl: string
          type: string
          user_id: string
        }
        Update: {
          action_url?: string | null
          body_en?: string | null
          body_pl?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_read?: boolean | null
          priority?: string | null
          read_at?: string | null
          title_en?: string
          title_pl?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          ambassador_status: string | null
          annual_leave_days: number | null
          available_from: string | null
          avatar_url: string | null
          bio: string | null
          certifications: Json | null
          clock_daily_summary_email: boolean
          created_at: string
          current_status: string | null
          cv_url: string | null
          default_location: string | null
          department: string | null
          desired_rate_max: number | null
          desired_rate_min: number | null
          education: Json | null
          email: string
          embedding: string | null
          employment_type: string | null
          experience_level: string | null
          experience_years: number | null
          fte_status: string | null
          full_name: string | null
          gdpr_consent: boolean | null
          github_url: string | null
          id: string
          is_inbox_handler: boolean
          job_title: string | null
          languages: string[] | null
          leaderboard_opt_out: boolean
          learning_streak_current: number
          learning_streak_last_date: string | null
          learning_streak_longest: number
          linkedin_url: string | null
          location: string | null
          loyalty_joined_at: string | null
          loyalty_points: number | null
          loyalty_tier: Database["public"]["Enums"]["loyalty_tier_t"]
          m365_synced_at: string | null
          manager_email: string | null
          max_monthly_hours: number | null
          onboarding_completed: boolean
          onboarding_tour_done: boolean
          phone: string | null
          portfolio_url: string | null
          preferred_language: string | null
          previous_clients: string[] | null
          profile_completion_percent: number | null
          project_sentiment: string | null
          role: Database["public"]["Enums"]["user_role"] | null
          sales_support_status: string | null
          skills: string[] | null
          verifier_status: string | null
          work_history: Json | null
          work_start_date: string | null
        }
        Insert: {
          ambassador_status?: string | null
          annual_leave_days?: number | null
          available_from?: string | null
          avatar_url?: string | null
          bio?: string | null
          certifications?: Json | null
          clock_daily_summary_email?: boolean
          created_at?: string
          current_status?: string | null
          cv_url?: string | null
          default_location?: string | null
          department?: string | null
          desired_rate_max?: number | null
          desired_rate_min?: number | null
          education?: Json | null
          email: string
          embedding?: string | null
          employment_type?: string | null
          experience_level?: string | null
          experience_years?: number | null
          fte_status?: string | null
          full_name?: string | null
          gdpr_consent?: boolean | null
          github_url?: string | null
          id: string
          is_inbox_handler?: boolean
          job_title?: string | null
          languages?: string[] | null
          leaderboard_opt_out?: boolean
          learning_streak_current?: number
          learning_streak_last_date?: string | null
          learning_streak_longest?: number
          linkedin_url?: string | null
          location?: string | null
          loyalty_joined_at?: string | null
          loyalty_points?: number | null
          loyalty_tier?: Database["public"]["Enums"]["loyalty_tier_t"]
          m365_synced_at?: string | null
          manager_email?: string | null
          max_monthly_hours?: number | null
          onboarding_completed?: boolean
          onboarding_tour_done?: boolean
          phone?: string | null
          portfolio_url?: string | null
          preferred_language?: string | null
          previous_clients?: string[] | null
          profile_completion_percent?: number | null
          project_sentiment?: string | null
          role?: Database["public"]["Enums"]["user_role"] | null
          sales_support_status?: string | null
          skills?: string[] | null
          verifier_status?: string | null
          work_history?: Json | null
          work_start_date?: string | null
        }
        Update: {
          ambassador_status?: string | null
          annual_leave_days?: number | null
          available_from?: string | null
          avatar_url?: string | null
          bio?: string | null
          certifications?: Json | null
          clock_daily_summary_email?: boolean
          created_at?: string
          current_status?: string | null
          cv_url?: string | null
          default_location?: string | null
          department?: string | null
          desired_rate_max?: number | null
          desired_rate_min?: number | null
          education?: Json | null
          email?: string
          embedding?: string | null
          employment_type?: string | null
          experience_level?: string | null
          experience_years?: number | null
          fte_status?: string | null
          full_name?: string | null
          gdpr_consent?: boolean | null
          github_url?: string | null
          id?: string
          is_inbox_handler?: boolean
          job_title?: string | null
          languages?: string[] | null
          leaderboard_opt_out?: boolean
          learning_streak_current?: number
          learning_streak_last_date?: string | null
          learning_streak_longest?: number
          linkedin_url?: string | null
          location?: string | null
          loyalty_joined_at?: string | null
          loyalty_points?: number | null
          loyalty_tier?: Database["public"]["Enums"]["loyalty_tier_t"]
          m365_synced_at?: string | null
          manager_email?: string | null
          max_monthly_hours?: number | null
          onboarding_completed?: boolean
          onboarding_tour_done?: boolean
          phone?: string | null
          portfolio_url?: string | null
          preferred_language?: string | null
          previous_clients?: string[] | null
          profile_completion_percent?: number | null
          project_sentiment?: string | null
          role?: Database["public"]["Enums"]["user_role"] | null
          sales_support_status?: string | null
          skills?: string[] | null
          verifier_status?: string | null
          work_history?: Json | null
          work_start_date?: string | null
        }
        Relationships: []
      }
      projects: {
        Row: {
          budget_range: string | null
          created_at: string | null
          description: string
          embedding: string | null
          id: string
          required_skills: string[] | null
          title: string
        }
        Insert: {
          budget_range?: string | null
          created_at?: string | null
          description: string
          embedding?: string | null
          id?: string
          required_skills?: string[] | null
          title: string
        }
        Update: {
          budget_range?: string | null
          created_at?: string | null
          description?: string
          embedding?: string | null
          id?: string
          required_skills?: string[] | null
          title?: string
        }
        Relationships: []
      }
      public_holidays: {
        Row: {
          date: string
          name_pl: string
          year: number | null
        }
        Insert: {
          date: string
          name_pl: string
          year?: number | null
        }
        Update: {
          date?: string
          name_pl?: string
          year?: number | null
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          last_used_at: string
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          last_used_at?: string
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          last_used_at?: string
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      support_articles: {
        Row: {
          author_id: string
          category_id: string
          content_md: string
          created_at: string
          excerpt: string | null
          id: string
          published_at: string | null
          slug: string
          title: string
          updated_at: string
        }
        Insert: {
          author_id: string
          category_id: string
          content_md: string
          created_at?: string
          excerpt?: string | null
          id?: string
          published_at?: string | null
          slug: string
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          category_id?: string
          content_md?: string
          created_at?: string
          excerpt?: string | null
          id?: string
          published_at?: string | null
          slug?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_articles_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_articles_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "support_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      support_categories: {
        Row: {
          created_at: string
          icon: string
          id: string
          name_en: string
          name_pl: string
          slug: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          icon?: string
          id?: string
          name_en: string
          name_pl: string
          slug: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          icon?: string
          id?: string
          name_en?: string
          name_pl?: string
          slug?: string
          sort_order?: number
        }
        Relationships: []
      }
      support_inbox_meta: {
        Row: {
          consultant_id: string | null
          created_at: string
          due_date: string
          email_from: string | null
          email_received_at: string | null
          email_subject: string | null
          external_message_id: string | null
          priority_level: string
          source: string
          ticket_id: string
        }
        Insert: {
          consultant_id?: string | null
          created_at?: string
          due_date: string
          email_from?: string | null
          email_received_at?: string | null
          email_subject?: string | null
          external_message_id?: string | null
          priority_level?: string
          source?: string
          ticket_id: string
        }
        Update: {
          consultant_id?: string | null
          created_at?: string
          due_date?: string
          email_from?: string | null
          email_received_at?: string | null
          email_subject?: string | null
          external_message_id?: string | null
          priority_level?: string
          source?: string
          ticket_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_inbox_meta_consultant_id_fkey"
            columns: ["consultant_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_inbox_meta_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: true
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_ticket_comments: {
        Row: {
          author_id: string
          body_md: string
          created_at: string
          id: string
          is_internal: boolean
          ticket_id: string
        }
        Insert: {
          author_id: string
          body_md: string
          created_at?: string
          id?: string
          is_internal?: boolean
          ticket_id: string
        }
        Update: {
          author_id?: string
          body_md?: string
          created_at?: string
          id?: string
          is_internal?: boolean
          ticket_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_ticket_comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_ticket_comments_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: false
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          assignee_id: string | null
          body_md: string
          category_id: string
          created_at: string
          id: string
          priority: string
          resolved_at: string | null
          status: string
          subject: string
          updated_at: string
          user_id: string
        }
        Insert: {
          assignee_id?: string | null
          body_md: string
          category_id: string
          created_at?: string
          id?: string
          priority?: string
          resolved_at?: string | null
          status?: string
          subject: string
          updated_at?: string
          user_id: string
        }
        Update: {
          assignee_id?: string | null
          body_md?: string
          category_id?: string
          created_at?: string
          id?: string
          priority?: string
          resolved_at?: string | null
          status?: string
          subject?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "support_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      system_settings: {
        Row: {
          description: string | null
          id: string
          key: string
          updated_at: string
          updated_by: string | null
          value: string
        }
        Insert: {
          description?: string | null
          id?: string
          key: string
          updated_at?: string
          updated_by?: string | null
          value: string
        }
        Update: {
          description?: string | null
          id?: string
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: string
        }
        Relationships: [
          {
            foreignKeyName: "system_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_activity: {
        Row: {
          action: string
          created_at: string | null
          details: Json | null
          id: string
          task_id: string
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string | null
          details?: Json | null
          id?: string
          task_id: string
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string | null
          details?: Json | null
          id?: string
          task_id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "task_activity_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_activity_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_assignments: {
        Row: {
          assigned_at: string | null
          task_id: string
          user_id: string
        }
        Insert: {
          assigned_at?: string | null
          task_id: string
          user_id: string
        }
        Update: {
          assigned_at?: string | null
          task_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_assignments_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_boards: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          is_shared: boolean | null
          name: string
          owner_id: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_shared?: boolean | null
          name: string
          owner_id?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_shared?: boolean | null
          name?: string
          owner_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "task_boards_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_columns: {
        Row: {
          board_id: string
          color: string | null
          created_at: string | null
          id: string
          name: string
          position: number
        }
        Insert: {
          board_id: string
          color?: string | null
          created_at?: string | null
          id?: string
          name: string
          position?: number
        }
        Update: {
          board_id?: string
          color?: string | null
          created_at?: string | null
          id?: string
          name?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "task_columns_board_id_fkey"
            columns: ["board_id"]
            isOneToOne: false
            referencedRelation: "task_boards"
            referencedColumns: ["id"]
          },
        ]
      }
      task_comments: {
        Row: {
          author_id: string | null
          content: string
          created_at: string | null
          id: string
          task_id: string
        }
        Insert: {
          author_id?: string | null
          content: string
          created_at?: string | null
          id?: string
          task_id: string
        }
        Update: {
          author_id?: string | null
          content?: string
          created_at?: string | null
          id?: string
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_comments_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          board_id: string | null
          column_id: string | null
          created_at: string | null
          created_by: string | null
          description: string | null
          due_date: string | null
          id: string
          position: number | null
          priority: string | null
          status: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          board_id?: string | null
          column_id?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          position?: number | null
          priority?: string | null
          status?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          board_id?: string | null
          column_id?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          position?: number | null
          priority?: string | null
          status?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_board_id_fkey"
            columns: ["board_id"]
            isOneToOne: false
            referencedRelation: "task_boards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_column_id_fkey"
            columns: ["column_id"]
            isOneToOne: false
            referencedRelation: "task_columns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      timesheet_entries: {
        Row: {
          correction_decided_at: string | null
          correction_decided_by: string | null
          correction_decision_note: string | null
          correction_required: boolean
          created_at: string
          description: string
          hours: number
          id: string
          project: string | null
          source: string
          timesheet_id: string
          tracked_hours: number | null
          work_date: string
        }
        Insert: {
          correction_decided_at?: string | null
          correction_decided_by?: string | null
          correction_decision_note?: string | null
          correction_required?: boolean
          created_at?: string
          description: string
          hours: number
          id?: string
          project?: string | null
          source?: string
          timesheet_id: string
          tracked_hours?: number | null
          work_date: string
        }
        Update: {
          correction_decided_at?: string | null
          correction_decided_by?: string | null
          correction_decision_note?: string | null
          correction_required?: boolean
          created_at?: string
          description?: string
          hours?: number
          id?: string
          project?: string | null
          source?: string
          timesheet_id?: string
          tracked_hours?: number | null
          work_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "timesheet_entries_correction_decided_by_fkey"
            columns: ["correction_decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "timesheet_entries_timesheet_id_fkey"
            columns: ["timesheet_id"]
            isOneToOne: false
            referencedRelation: "timesheets"
            referencedColumns: ["id"]
          },
        ]
      }
      timesheet_timers: {
        Row: {
          converted_entry_id: string | null
          created_at: string
          deprecated_at: string | null
          description: string
          hours_calculated: number | null
          id: string
          project: string | null
          started_at: string
          stopped_at: string | null
          user_id: string
          work_date: string
        }
        Insert: {
          converted_entry_id?: string | null
          created_at?: string
          deprecated_at?: string | null
          description?: string
          hours_calculated?: number | null
          id?: string
          project?: string | null
          started_at?: string
          stopped_at?: string | null
          user_id: string
          work_date?: string
        }
        Update: {
          converted_entry_id?: string | null
          created_at?: string
          deprecated_at?: string | null
          description?: string
          hours_calculated?: number | null
          id?: string
          project?: string | null
          started_at?: string
          stopped_at?: string | null
          user_id?: string
          work_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "timesheet_timers_converted_entry_id_fkey"
            columns: ["converted_entry_id"]
            isOneToOne: false
            referencedRelation: "timesheet_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "timesheet_timers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      timesheets: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          auto_filled_at: string | null
          created_at: string
          id: string
          month: number
          pdf_hash: string | null
          rejection_note: string | null
          status: string
          submitted_at: string | null
          updated_at: string
          user_cleared_auto_fill: boolean
          user_id: string
          year: number
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          auto_filled_at?: string | null
          created_at?: string
          id?: string
          month: number
          pdf_hash?: string | null
          rejection_note?: string | null
          status?: string
          submitted_at?: string | null
          updated_at?: string
          user_cleared_auto_fill?: boolean
          user_id: string
          year: number
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          auto_filled_at?: string | null
          created_at?: string
          id?: string
          month?: number
          pdf_hash?: string | null
          rejection_note?: string | null
          status?: string
          submitted_at?: string | null
          updated_at?: string
          user_cleared_auto_fill?: boolean
          user_id?: string
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "timesheets_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "timesheets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      um_legal_documents: {
        Row: {
          content: string
          created_at: string | null
          document_type: string
          effective_date: string
          id: string
          is_active: boolean | null
          title: string
          updated_at: string | null
          version: string
        }
        Insert: {
          content: string
          created_at?: string | null
          document_type: string
          effective_date: string
          id?: string
          is_active?: boolean | null
          title: string
          updated_at?: string | null
          version: string
        }
        Update: {
          content?: string
          created_at?: string | null
          document_type?: string
          effective_date?: string
          id?: string
          is_active?: boolean | null
          title?: string
          updated_at?: string | null
          version?: string
        }
        Relationships: []
      }
      um_user_consents: {
        Row: {
          accepted_ai: boolean
          accepted_at: string
          accepted_data_processing: boolean
          accepted_ip: unknown
          accepted_privacy: boolean
          accepted_terms: boolean
          accepted_ua: string | null
          created_at: string
          id: string
          terms_version: string
          user_id: string
        }
        Insert: {
          accepted_ai?: boolean
          accepted_at?: string
          accepted_data_processing?: boolean
          accepted_ip?: unknown
          accepted_privacy?: boolean
          accepted_terms?: boolean
          accepted_ua?: string | null
          created_at?: string
          id?: string
          terms_version: string
          user_id: string
        }
        Update: {
          accepted_ai?: boolean
          accepted_at?: string
          accepted_data_processing?: boolean
          accepted_ip?: unknown
          accepted_privacy?: boolean
          accepted_terms?: boolean
          accepted_ua?: string | null
          created_at?: string
          id?: string
          terms_version?: string
          user_id?: string
        }
        Relationships: []
      }
      verification_codes: {
        Row: {
          code: string
          created_at: string | null
          expires_at: string
          id: string
          type: string
          used_at: string | null
          user_id: string | null
        }
        Insert: {
          code: string
          created_at?: string | null
          expires_at: string
          id?: string
          type: string
          used_at?: string | null
          user_id?: string | null
        }
        Update: {
          code?: string
          created_at?: string | null
          expires_at?: string
          id?: string
          type?: string
          used_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      work_clock_consents: {
        Row: {
          accepted_at: string
          accepted_ip: unknown
          accepted_ua: string | null
          revoked_at: string | null
          revoked_reason: string | null
          terms_version: string
          user_id: string
        }
        Insert: {
          accepted_at?: string
          accepted_ip?: unknown
          accepted_ua?: string | null
          revoked_at?: string | null
          revoked_reason?: string | null
          terms_version: string
          user_id: string
        }
        Update: {
          accepted_at?: string
          accepted_ip?: unknown
          accepted_ua?: string | null
          revoked_at?: string | null
          revoked_reason?: string | null
          terms_version?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_consents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      work_clock_heartbeats: {
        Row: {
          id: number
          is_trusted: boolean
          page_visible: boolean
          session_id: string
          ts: string
          was_active: boolean
        }
        Insert: {
          id?: number
          is_trusted?: boolean
          page_visible?: boolean
          session_id: string
          ts: string
          was_active: boolean
        }
        Update: {
          id?: number
          is_trusted?: boolean
          page_visible?: boolean
          session_id?: string
          ts?: string
          was_active?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_heartbeats_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "work_clock_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      work_clock_route_metadata: {
        Row: {
          created_at: string
          id: number
          page_title: string | null
          route_path: string
          session_id: string
          ts_bucket_5min: string
        }
        Insert: {
          created_at?: string
          id?: number
          page_title?: string | null
          route_path: string
          session_id: string
          ts_bucket_5min: string
        }
        Update: {
          created_at?: string
          id?: number
          page_title?: string | null
          route_path?: string
          session_id?: string
          ts_bucket_5min?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_route_metadata_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "work_clock_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      work_clock_session_pauses: {
        Row: {
          created_by: string | null
          id: number
          pause_reason: string
          paused_at: string
          resumed_at: string | null
          session_id: string
        }
        Insert: {
          created_by?: string | null
          id?: number
          pause_reason: string
          paused_at?: string
          resumed_at?: string | null
          session_id: string
        }
        Update: {
          created_by?: string | null
          id?: number
          pause_reason?: string
          paused_at?: string
          resumed_at?: string | null
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_session_pauses_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "work_clock_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      work_clock_sessions: {
        Row: {
          active_seconds: number
          client_tz: string
          closed_reason: string | null
          created_at: string
          created_by: string | null
          device_label: string | null
          ended_at: string | null
          id: string
          idle_seconds: number
          last_heartbeat: string
          location: string
          merged_from_session_id: string | null
          pause_reason: string | null
          paused_until: string | null
          route_tracking_enabled: boolean
          started_at: string
          updated_at: string
          user_disregarded: boolean
          user_id: string
        }
        Insert: {
          active_seconds?: number
          client_tz?: string
          closed_reason?: string | null
          created_at?: string
          created_by?: string | null
          device_label?: string | null
          ended_at?: string | null
          id?: string
          idle_seconds?: number
          last_heartbeat: string
          location: string
          merged_from_session_id?: string | null
          pause_reason?: string | null
          paused_until?: string | null
          route_tracking_enabled?: boolean
          started_at: string
          updated_at?: string
          user_disregarded?: boolean
          user_id: string
        }
        Update: {
          active_seconds?: number
          client_tz?: string
          closed_reason?: string | null
          created_at?: string
          created_by?: string | null
          device_label?: string | null
          ended_at?: string | null
          id?: string
          idle_seconds?: number
          last_heartbeat?: string
          location?: string
          merged_from_session_id?: string | null
          pause_reason?: string | null
          paused_until?: string | null
          route_tracking_enabled?: boolean
          started_at?: string
          updated_at?: string
          user_disregarded?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_sessions_merged_from_session_id_fkey"
            columns: ["merged_from_session_id"]
            isOneToOne: false
            referencedRelation: "work_clock_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_clock_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      work_clock_daily: {
        Row: {
          active_seconds: number | null
          first_clock_in: string | null
          hours: number | null
          last_clock_out: string | null
          session_count: number | null
          user_id: string | null
          work_date: string | null
        }
        Relationships: [
          {
            foreignKeyName: "work_clock_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      admin_revoke_user_sessions: {
        Args: { target_user_id: string }
        Returns: undefined
      }
      award_course_points: {
        Args: { p_enrollment_id: string }
        Returns: string
      }
      award_first_publish_bonus: {
        Args: { p_course_id: string }
        Returns: string
      }
      create_notification: {
        Args: {
          p_action_url?: string
          p_body_en?: string
          p_body_pl?: string
          p_priority?: string
          p_title_en: string
          p_title_pl: string
          p_type: string
          p_user_id: string
        }
        Returns: string
      }
      expire_old_notifications: { Args: never; Returns: undefined }
      get_quiz_for_attempt: {
        Args: { p_course_id: string }
        Returns: {
          options: Json
          question_id: string
          question_order: number
          question_text: string
        }[]
      }
      is_admin: { Args: never; Returns: boolean }
      is_inbox_category: { Args: { p_category_id: string }; Returns: boolean }
      is_inbox_handler: { Args: never; Returns: boolean }
      is_internal_or_admin: { Args: never; Returns: boolean }
      is_trainer_or_admin: { Args: never; Returns: boolean }
      match_assist_knowledge: {
        Args: {
          filter_category?: string
          match_count: number
          match_threshold: number
          query_embedding: string
        }
        Returns: {
          category: string
          content: string
          id: string
          similarity: number
          title: string
        }[]
      }
      match_courses: {
        Args: {
          match_count?: number
          match_threshold?: number
          query_embedding: string
        }
        Returns: {
          course_id: string
          similarity: number
        }[]
      }
      submit_quiz_attempt: {
        Args: { p_answers: Json; p_course_id: string }
        Returns: Json
      }
      sync_user_role: {
        Args: { p_email: string; p_is_super_admin?: boolean; p_user_id: string }
        Returns: Database["public"]["Enums"]["user_role"]
      }
    }
    Enums: {
      candidate_interested_status: "yes" | "no" | "not_asked"
      course_type_t: "consultant" | "company"
      engagement_type:
        | "full_time"
        | "half_time"
        | "3_4_days"
        | "to_be_discussed"
      loyalty_tier_t:
        | "scout"
        | "explorer"
        | "pathfinder"
        | "navigator"
        | "captain"
        | "admiral"
        | "legend"
      referral_status:
        | "new"
        | "in_review"
        | "accepted"
        | "rejected"
        | "hired"
        | "withdrawn"
      referral_type: "external_person" | "self_referral"
      relationship_type:
        | "coworker"
        | "industry_contact"
        | "former_project"
        | "linkedin"
        | "other"
      user_role: "consultant" | "admin" | "internal"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      candidate_interested_status: ["yes", "no", "not_asked"],
      course_type_t: ["consultant", "company"],
      engagement_type: [
        "full_time",
        "half_time",
        "3_4_days",
        "to_be_discussed",
      ],
      loyalty_tier_t: [
        "scout",
        "explorer",
        "pathfinder",
        "navigator",
        "captain",
        "admiral",
        "legend",
      ],
      referral_status: [
        "new",
        "in_review",
        "accepted",
        "rejected",
        "hired",
        "withdrawn",
      ],
      referral_type: ["external_person", "self_referral"],
      relationship_type: [
        "coworker",
        "industry_contact",
        "former_project",
        "linkedin",
        "other",
      ],
      user_role: ["consultant", "admin", "internal"],
    },
  },
} as const
