-- A placement normally generates two bonuses (Delivery Lead + recruiter).
-- Business rule: when Igor Twardowski is the canonical Delivery Lead, Marcin
-- Kraszewski receives a second, independently selectable DL bonus. Keep the
-- generated row linked to the placement so confirmation stays idempotent and
-- later deletion/compensation can account for all three bonuses.

BEGIN;

ALTER TABLE public.placements
    ADD COLUMN IF NOT EXISTS additional_dl_bonus_id UUID
        REFERENCES public.bonuses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_placements_additional_dl_bonus_id
    ON public.placements(additional_dl_bonus_id);

COMMENT ON COLUMN public.placements.additional_dl_bonus_id IS
    'Optional second Delivery Lead bonus generated by the Igor Twardowski to Marcin Kraszewski placement rule.';

COMMIT;
