'use client'

import { useState } from 'react'
import { BookOpen, Clock3, Download, Eye, ListChecks } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { MarkdownView } from '@/components/learning/MarkdownView'
import { EmbedVideo } from '@/components/learning/EmbedVideo'
import type { CourseDetail, CourseLesson, CourseQuizQuestionAuthor } from '@/lib/types/learning'
import { AcademyVideo } from './AcademyVideo'
import { lessonCaptionForVideo } from '@/lib/academy/lesson-captions'
import { COURSE_FORMAT_LABELS, COURSE_LEVEL_LABELS } from './catalog/catalog-filters'

export function CourseLearnerPreview({ course, lessons, quiz, mode: previewMode = 'editor' }: { mode?: 'editor' | 'instructor' | 'review'; course: CourseDetail; lessons: CourseLesson[]; quiz: CourseQuizQuestionAuthor[] }) {
    const [selected, setSelected] = useState<string | null>(null)
    const [answers, setAnswers] = useState<Record<string, string>>({})
    const [score, setScore] = useState<number | null>(null)
    const lesson = lessons.find((item) => item.id === selected) ?? lessons[0]
    const videos = lesson?.attachments.filter((item) => item.asset_id && item.mime_type === 'video/mp4') ?? []
    const mode = course.delivery_mode ?? 'self_paced'
    const rules = course.completion_rules
    return <div className="space-y-5">
        <div role="note" className="flex items-start gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><Eye className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" /><p>{previewMode === 'review' ? `Podgląd wersji ${course.version_number ?? 1} do decyzji moderatora. Sprawdź program, pliki i warunki ukończenia.` : previewMode === 'instructor' ? `Zatwierdzony program przypisany do tej edycji — wersja ${course.version_number ?? 1}.` : `Podgląd zapisanych zmian w wersji ${course.version_number ?? 1}. Najpierw zapisz zmiany w edytorze.`} Ten widok nie tworzy zapisów, postępu, prób quizu ani certyfikatów.</p></div>
        <section className="space-y-4 rounded-2xl border border-border bg-card p-5 sm:p-6">
            <div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><span className="rounded-full bg-muted px-3 py-1">{COURSE_FORMAT_LABELS[mode]}</span><span className="rounded-full bg-muted px-3 py-1">{COURSE_LEVEL_LABELS[course.level ?? 'beginner']}</span><span className="rounded-full bg-muted px-3 py-1">{course.category}</span></div>
            <h2 className="break-words text-2xl font-semibold tracking-tight">{course.title}</h2>
            {course.description && <p className="whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">{course.description}</p>}
            <div className="space-y-2 rounded-xl bg-muted/40 p-4 text-sm"><h3 className="flex items-center gap-2 font-semibold"><ListChecks className="size-4" aria-hidden="true" />Warunki ukończenia</h3><ul className="list-inside list-disc space-y-1 text-muted-foreground">{rules?.require_all_lessons && <li>Ukończenie wszystkich lekcji</li>}{rules?.quiz_required && <li>Quiz: przynajmniej {rules.quiz_pass_percent}% poprawnych odpowiedzi</li>}{mode !== 'self_paced' && <li>Co najmniej {rules?.attendance_percent ?? 80}% obecności na każdej wymaganej sesji</li>}{!!course.prerequisite_course_ids?.length && <li>Wymagane wcześniejsze ukończenie szkoleń: {course.prerequisite_course_ids.length}</li>}</ul></div>
            {mode !== 'self_paced' && <p className="text-sm text-muted-foreground">Uczestnik wybiera termin i zapisuje się w edycji szkolenia. Terminy są zatwierdzane osobno.</p>}
        </section>
        {lessons.length > 0 ? <section className="grid items-start gap-5 lg:grid-cols-[240px_minmax(0,1fr)]" aria-label="Podgląd lekcji">
            <nav aria-label="Program w podglądzie" className="rounded-xl border border-border bg-card p-3"><h3 className="mb-3 flex items-center gap-2 px-2 text-sm font-semibold"><BookOpen className="size-4" aria-hidden="true" />Program szkolenia</h3><ol className="space-y-1">{lessons.map((item, index) => <li key={item.id}><button type="button" onClick={() => setSelected(item.id)} aria-current={item.id === lesson?.id ? 'step' : undefined} className={`w-full rounded-lg p-3 text-left text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${item.id === lesson?.id ? 'bg-primary/10 font-medium text-primary' : 'text-muted-foreground hover:bg-muted'}`}><span>{index + 1}. {item.title}</span>{item.unlock_after_days > 0 && <span className="mt-1 block text-xs font-normal">Odblokowanie {item.unlock_after_days} dni po poprzedniej lekcji</span>}</button></li>)}</ol></nav>
            {lesson && <article className="min-w-0 space-y-4 rounded-2xl border border-border bg-card p-5 sm:p-6"><h3 className="text-xl font-semibold">{lesson.title}</h3>{lesson.estimated_minutes && <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" aria-hidden="true" />{lesson.estimated_minutes} min</p>}{videos.map(video => <AcademyVideo key={video.asset_id} lessonId={lesson.id} video={video} captions={lessonCaptionForVideo(lesson.attachments, video.asset_id!)} />)}{lesson.video_url && <EmbedVideo url={lesson.video_url} title={lesson.title} />}{lesson.content_md && <MarkdownView content={lesson.content_md} />}{lesson.attachments.length > 0 && <div className="space-y-2 border-t border-border pt-4"><h4 className="text-sm font-semibold">Materiały do pobrania</h4>{lesson.attachments.map((item, index) => <a key={item.asset_id ?? `${item.storage_path}-${index}`} href={`/api/akademia/attachment?${new URLSearchParams({ lessonId: lesson.id, ...(item.asset_id ? { assetId: item.asset_id } : { path: item.storage_path }) })}`} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 rounded-lg border border-border p-3 text-sm text-primary hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Download aria-hidden="true" className="mt-0.5 size-4 shrink-0" /><span className="break-all">{item.name}<span className="sr-only"> (nowa karta)</span></span></a>)}</div>}{!lesson.content_md && !lesson.video_url && !lesson.attachments.length && <p className="text-sm text-muted-foreground">Lekcja nie ma jeszcze zapisanej treści.</p>}</article>}
        </section> : <p className="rounded-xl border border-border bg-muted/30 p-5 text-sm text-muted-foreground">{mode === 'live' ? 'Program jest realizowany podczas spotkań. Nie dodano osobnych lekcji.' : 'Po dodaniu lekcji zobaczysz tutaj ich treść.'}</p>}
        {quiz.length > 0 && <section className="space-y-5 rounded-2xl border border-border bg-card p-5 sm:p-6" aria-label="Podgląd quizu"><div><h3 className="text-lg font-semibold">Quiz — podgląd uczestnika</h3><p className="text-sm text-muted-foreground">Możesz sprawdzić działanie pytań. Wynik pozostaje tylko w tym podglądzie.</p></div>{quiz.map((question, index) => <fieldset key={question.id} className="space-y-2"><legend className="mb-3 text-sm font-medium">{index + 1}. {question.question_text}</legend>{question.options.map((option) => <label key={option.id} className="flex cursor-pointer items-start gap-3 rounded-lg border border-border p-3 text-sm hover:bg-muted/30"><input type="radio" name={`preview-${question.id}`} checked={answers[question.id] === option.id} onChange={() => { setAnswers((current) => ({ ...current, [question.id]: option.id })); setScore(null) }} className="mt-0.5 size-4 shrink-0 accent-primary" /><span>{option.option_text}</span></label>)}</fieldset>)}<Button type="button" disabled={quiz.some((question) => !answers[question.id])} onClick={() => setScore(Math.round(100 * quiz.filter((question) => question.options.some((option) => option.id === answers[question.id] && option.is_correct)).length / quiz.length))}>Sprawdź wynik w podglądzie</Button>{score !== null && <p role="status" className="rounded-lg bg-muted p-4 text-sm">Wynik podglądu: {score}%. {score >= (rules?.quiz_pass_percent ?? 70) ? 'Próg zaliczenia osiągnięty.' : 'Próg zaliczenia nie został osiągnięty.'} Nie zapisano próby quizu.</p>}</section>}
    </div>
}
